#%RAML 1.0 DataType

type: object

properties:

  incidentId:
    type: string

  customerId:
    type: string

  title:
    type: string

  description:
    type: string

  severity:
    type: string

  category:
    type: string

  contactEmail:
    type: string

  status:
    type: string

  correlationId:
    type: string

  createdAt:
    type: datetime